//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetCare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bnfcode
    {
        public int ID { get; set; }
        public string lnkdid { get; set; }
        public string c_strength { get; set; }
        public string c_bnf_code { get; set; }
        public Nullable<double> c_cd { get; set; }
    }
}
