//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetCare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedAdmin
    {
        public int ID { get; set; }
        public string admin_reason { get; set; }
        public Nullable<System.DateTime> administered_date { get; set; }
        public Nullable<System.TimeSpan> admin_time { get; set; }
        public Nullable<System.DateTime> charted_date { get; set; }
        public Nullable<System.TimeSpan> administered_time { get; set; }
        public string lnkpid { get; set; }
        public Nullable<decimal> lnkordid { get; set; }
        public string administrator { get; set; }
    }
}
