//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetCare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicine
    {
        public int ID { get; set; }
        public string DrugName { get; set; }
        public string Bnfcode { get; set; }
        public string Route { get; set; }
        public string ExclusionWards { get; set; }
        public int RiskFactor { get; set; }
        public bool IsHighRisk { get; set; }
        public bool IsMediumRisk { get; set; }
        public bool POPAANPTA { get; set; }
        public bool IsVTE { get; set; }
        public bool IsCautious { get; set; }
        public bool IsMissedDoseNotification { get; set; }
    }
}
