//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetCare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class patientmed
    {
        public int ID { get; set; }
        public string lnkpid { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<double> lnkspell { get; set; }
        public string drug_description { get; set; }
        public string prn { get; set; }
        public string stat { get; set; }
        public string status { get; set; }
        public string frequency_description { get; set; }
        public string freeform_frequency { get; set; }
        public Nullable<double> primary_dose { get; set; }
        public Nullable<System.DateTime> change_start_date { get; set; }
        public Nullable<System.DateTime> change_start_time { get; set; }
        public string stop_date { get; set; }
        public Nullable<double> lnkordid { get; set; }
        public string stop_time { get; set; }
        public string route { get; set; }
        public string self_administer { get; set; }
        public string prescribing_drug_id { get; set; }
        public string order_type { get; set; }
        public Nullable<System.DateTime> suspend_date { get; set; }
        public Nullable<System.DateTime> suspend_time { get; set; }
        public Nullable<System.DateTime> resume_date { get; set; }
        public Nullable<System.DateTime> resume_time { get; set; }
        public string suspend_reason { get; set; }
    }
}
