//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetCare.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Scheduler
    {
        public int SchedulerID { get; set; }
        public Nullable<int> InspectorID { get; set; }
        public System.DateTime ScheduleDate { get; set; }
        public Nullable<System.DateTime> ScheduleTime { get; set; }
        public string ScheduleTitle { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public int SomeImportantKey { get; set; }
        public int StatusENUM { get; set; }
        public int AppointmentLength { get; set; }
    }
}
