//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetCare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class specialconsideration
    {
        public int ID { get; set; }
        public string drug_speccon { get; set; }
        public string lnkdid { get; set; }
        public Nullable<double> piece_no { get; set; }
        public string speccon_description { get; set; }
        public string drug_basic_common { get; set; }
        public string lnkdid1 { get; set; }
        public string c_drugname { get; set; }
        public string c_strength { get; set; }
        public string c_form { get; set; }
        public string c_bnf_code { get; set; }
    }
}
