//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetCare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class verified
    {
        public int ID { get; set; }
        public string status { get; set; }
        public string verified_by { get; set; }
        public Nullable<System.DateTime> verify_date { get; set; }
        public Nullable<System.DateTime> verify_time { get; set; }
        public Nullable<double> lnkordid { get; set; }
        public string lnkpid { get; set; }
        public Nullable<System.DateTime> change_start_date { get; set; }
        public Nullable<System.DateTime> change_start_time { get; set; }
    }
}
